max_n_bars: 32

se_d_model: 128
se_d_ff: 256
se_n_layers: 2
se_n_heads: 4
se_n_src1_voices: 1
se_n_src2_voices: 0
se_steps_per_segment: 4
se_has_velocity: true
se_has_offset: true
se_dropout: 0.1
se_velocity_dropout: 0.1
se_offset_dropout: 0.1
se_positional_dropout: 0.1

pe_d_model: 128
pe_d_ff: 256
pe_n_layers: 4
pe_n_heads: 4
pe_max_n_segments: 32
pe_dropout: 0.1
pe_positional_dropout: 0.1

dc_d_model: 128
dc_d_ff: 256
dc_n_layers: 6
dc_n_heads: 4
dc_n_tgt_voices: 9

dc_dropout: 0.1
dc_velocity_dropout: 0.3
dc_offset_dropout: 0.3
dc_positional_dropout: 0.1
dc_has_velocity: false
dc_has_offset: true

scale_h_loss: 1
scale_v_loss: 1.7
scale_o_loss: 0.5

optimizer: "adam"
lr: 0.0006369948608989782
batch_size: 96
epochs: 1000
device: "cuda"

input_inst_dataset_bz2_filepath_train: "data/lmd/data_bass_groove_train.bz2"
output_inst_dataset_bz2_filepath_train: "data/lmd/data_drums_full_unsplit.bz2"
input_inst_dataset_bz2_filepath_test: "data/lmd/data_bass_groove_test.bz2"
output_inst_dataset_bz2_filepath_test: "data/lmd/data_drums_full_unsplit.bz2"
shift_tgt_by_n_steps: 1
hop_n_bars: 8

upload_to_wandb: false
save_model_frequency: 5
push_all_data_to_cuda: false
teacher_forcing_ratio: 1.0
start_decoder_training_at_epoch: 5
run_name: "TOMS_WEIGHTED_MORE_freezing_decoder_initially_AND_bass_vel_only"


