max_n_bars: 32
input_has_velocity: false
d_model: 64
d_ff: 128
n_layers: 6
n_heads: 4
n_src1_voices: 1
n_src2_voices: 9
dropout: 0.0
positional_encoding_dropout: 0.0

scale_h_loss: 1
scale_v_loss: 1
scale_o_loss: 1

optimizer: "adam"
lr: 0.0006369948608989782
batch_size: 128
epochs: 1000
device: "cuda"

train_datasets:
  - "data/lmd/data_bass_groove_train.bz2"
  - "data/lmd/data_guitar_groove_train.bz2"
  - "data/lmd/data_synth_groove_train.bz2"
  - "data/lmd/data_lead_groove_train.bz2"
  - "data/lmd/data_piano_groove_train.bz2"

test_datasets:
  - "data/lmd/data_bass_groove_test.bz2"
  - "data/lmd/data_guitar_groove_test.bz2"
  - "data/lmd/data_synth_groove_test.bz2"
  - "data/lmd/data_lead_groove_test.bz2"
  - "data/lmd/data_piano_groove_test.bz2"

paired_drum_dataset_bz2_filepath_train: "data/lmd/data_drums_full_unsplit.bz2"
paired_drum_dataset_bz2_filepath_test: "data/lmd/data_drums_full_unsplit.bz2"

shift_tgt_by_n_steps: 1
hop_n_bars: 4

upload_to_wandb: false
save_model_frequency: 5
push_all_data_to_cuda: false
teacher_forcing_ratio: 1.0

predict_K_bars_ahead: 1

run_name: "[bassGuiSynLeadPian] (LTA_Stacked) 1bar no in vel"


