batch_size: 64
beta_annealing_activated: true
beta_annealing_per_cycle_period: 50
beta_annealing_per_cycle_rising_ratio: 0.25
beta_annealing_start_first_rise_at_epoch: 1
beta_level: 0.5
d_model_dec: 16
d_model_enc: 16
bz2dataset_path: "data/lmd/bass2drum_balanced.bz2pickle"
device: "cuda"
dim_feedforward_dec: 16
dim_feedforward_enc: 16
dropout: 0.1
embedding_size_src: 3
embedding_size_tgt: 3
epochs: 200
is_testing: false
latent_dim: 128
lr: 0.0006369948608989782
max_len_dec: 32
max_len_enc: 32
n_genres: 9      # Only used for MuteGenreLatentVAE
n_global_density_bins: 10
nhead_dec: 4
nhead_enc: 4
num_decoder_layers: 4
num_encoder_layers: 4
offset_dropout: 0.4
optimizer: "adam"
velocity_dropout: 0.4
scale_h_loss: 0.5
scale_v_loss: 3
scale_o_loss: 20
