max_n_bars: 32


steps_per_segment: 1
input_has_velocity: false
d_model: 128
d_ff: 256
n_layers: 6
n_heads: 4
n_drum_voices: 9
n_groove_voices: 1
dropout: 0.0

scale_h_loss: 1
scale_v_loss: 1.7
scale_o_loss: 0.5

optimizer: "adam"
lr: 0.0006369948608989782
batch_size: 32
epochs: 1000
device: "cuda"

input_inst_dataset_bz2_filepath_train: "data/lmd/data_bass_groove_train.bz2"
output_inst_dataset_bz2_filepath_train: "data/lmd/data_drums_full_unsplit.bz2"
input_inst_dataset_bz2_filepath_test: "data/lmd/data_bass_groove_test.bz2"
output_inst_dataset_bz2_filepath_test: "data/lmd/data_drums_full_unsplit.bz2"
shift_tgt_by_n_steps: 1
hop_n_bars: 1

upload_to_wandb: false
save_model_frequency: 5
push_all_data_to_cuda: false
teacher_forcing_ratio: 1.0
start_decoder_training_at_epoch: 5

predict_K_bars_ahead: 1

run_name: "(Smaller) Predict 1 bar ahead, no velocity at inputs"


